# Site settings
title: Hendra Manudinata
email: hendra@manudinata.me
description: >-
  Middle school student, loves fried rice and rendang! 🥓
url: "https://www.manudinata.me"
baseurl: ""

# Social
github_username: hendramanudinata03

# Pages (header button)
header_pages:
  GitHub: "https://github.com/hendramanudinata03"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

# Jekyll collections
# https://jekyllrb.com/docs/collections/
# https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_config.yml#L133-L136
collections:
  pages:
    output: true
    sort_by: order

# Default scopes
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
# https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_config.yml#L138-L148
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: page
      permalink: /blog/:title/
      comments: true

# Jekyll Admin configuration
jekyll_admin:
  hidden_links:
    - datafiles
