# Site settings
title: Hendra Manudinata
email: hendra@manudinata.me
description: >-
  Middle school student, loves fried rice and rendang! 🥓
url: "https://www.manudinata.me"
baseurl: ""

# Social
github_username: hendramanudinata03

# Pages (header button)
header_pages:
  GitHub: "https://github.com/hendramanudinata03"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
